export function inspectText(){
const visible=e=>{for(let a=e;a;a=a.parentElement){const s=getComputedStyle(a);if(s.display==='none'||s.visibility==='hidden'||+s.opacity<.18)return false}return true};
const nodes=[...document.querySelectorAll('.stage h2,.stage p,.stage .prelude,.stage .love,.stage .opening-foot>span,.stage .chapter-kicker,.stage .little-copy>span,#clock-time,.waiting-line,#typed-thought,.late-copy,.bridge-copy,.masthead a,.masthead button,.film-footer button,#chapter-label,#hold-memory,#scene-action')].filter(visible);
const meter=document.createElement('canvas').getContext('2d');
const items=nodes.map(e=>{const boxes=[],walker=document.createTreeWalker(e,NodeFilter.SHOW_TEXT);let node;
while(node=walker.nextNode()){if(!visible(node.parentElement))continue;const st=getComputedStyle(node.parentElement);meter.font=`${st.fontStyle} ${st.fontWeight} ${st.fontSize} ${st.fontFamily}`;for(let k=0;k<node.length;k++){if(!node.textContent[k].trim())continue;const range=document.createRange();range.setStart(node,k);range.setEnd(node,k+1);const r=range.getBoundingClientRect(),m=meter.measureText(node.textContent[k]),scale=r.height/(m.fontBoundingBoxAscent+m.fontBoundingBoxDescent);const baseline=r.y+m.fontBoundingBoxAscent*scale;boxes.push({x:r.x,y:baseline-m.actualBoundingBoxAscent*scale,r:r.right,b:baseline+m.actualBoundingBoxDescent*scale})}}
return {text:e.textContent,id:e.id||((e.closest('.scene-type,.shot-copy,.opening-foot')?.id||'')+' '+e.tagName+'.'+e.className),boxes}});
const collisions=[];for(let i=0;i<items.length;i++)for(let j=i+1;j<items.length;j++){const a=items[i],b=items[j];if(a.boxes.some(x=>b.boxes.some(y=>Math.min(x.r,y.r)-Math.max(x.x,y.x)>3&&Math.min(x.b,y.b)-Math.max(x.y,y.y)>3)))collisions.push([a.id,b.id])}
return {collisions,clipped:items.filter(a=>!a.id.endsWith('DIV.love')&&a.boxes.some(r=>r.x< -2||r.r>innerWidth+2||r.y<0||r.b>innerHeight)).map(a=>a.id),overflow:document.documentElement.scrollWidth>innerWidth,chapter:document.querySelector('#world').dataset.chapter};}
