import {clamp,progress,smooth,cover} from './timeline.mjs';
/** Two optional, accessible scene interactions; all artwork remains original V4 material. */
export function memories({state,wake,signal}){
 const action=document.querySelector('#scene-action'),dialog=document.querySelector('#memory-dialog'),card=document.querySelector('#memory-card'),picture=document.querySelector('#memory-picture'),note=document.querySelector('#memory-note'),turn=document.querySelector('#turn-memory');
 const mask=document.createElement('canvas'),mist=document.createElement('canvas');mask.width=mist.width=640;mask.height=mist.height=480;const m=mask.getContext('2d'),f=mist.getContext('2d');let mode='',cleared=false,dragging=false,last=null,returnFocus=null;
 function frost(){m.globalCompositeOperation='source-over';m.clearRect(0,0,640,480);const x=m.createLinearGradient(0,0,640,0);x.addColorStop(0,'transparent');x.addColorStop(.16,'#fff');x.addColorStop(.84,'#fff');x.addColorStop(1,'transparent');m.fillStyle=x;m.fillRect(0,0,640,480);m.globalCompositeOperation='destination-in';const y=m.createLinearGradient(0,0,0,480);y.addColorStop(0,'transparent');y.addColorStop(.18,'#fff');y.addColorStop(.75,'#fff');y.addColorStop(1,'transparent');m.fillStyle=y;m.fillRect(0,0,640,480);cleared=false;last=null}
 frost();
 function area({w,h,mobile}){return mobile?{x:w*.02,y:h*.08,w:w*.96,h:h*.58}:{x:w*.535,y:h*.035,w:w*.455,h:h*.69}}
 function erase(e){const s=state();if(mode!=='waiting'||dialog.open||e.target.closest('button,a'))return;const r=area(s),x=(e.clientX-r.x)/r.w*640,y=(e.clientY-r.y)/r.h*480;if(x<0||y<0||x>640||y>480){last=null;return}m.globalCompositeOperation='destination-out';m.lineWidth=s.mobile?85:64;m.lineCap='round';m.strokeStyle='#000';m.beginPath();m.moveTo(last?.x??x,last?.y??y);m.lineTo(x+.01,y);m.stroke();last={x,y};wake()}
 const on=(el,event,fn,options={})=>el.addEventListener(event,fn,{...options,signal});
 on(window,'pointerdown',e=>{dragging=true;last=null;erase(e)},{passive:true});on(window,'pointermove',e=>{if(dragging)erase(e)},{passive:true});on(window,'pointerup',()=>{dragging=false;last=null},{passive:true});on(window,'pointercancel',()=>{dragging=false;last=null},{passive:true});
 function open(){returnFocus=document.activeElement;const s=state();picture.src=mode==='little'?'/art/hero-cafe.webp':'/art/us-street.webp';picture.alt=mode==='little'?'Two unfinished coffees beside a rainy window':'Two takeaway cups and a red flower beneath an umbrella';note.textContent=mode==='little'?'I wanted the evening to last.':'I would take the long way again.';card.dataset.turned='false';document.querySelector('.memory-front').setAttribute('aria-hidden','false');document.querySelector('.memory-back').setAttribute('aria-hidden','true');turn.textContent='Turn it over';document.body.classList.add('memory-open');dialog.showModal();document.querySelector('#close-memory').focus();wake()}
 on(action,'click',()=>{if(mode==='waiting'){if(cleared)frost();else{m.clearRect(0,0,640,480);cleared=true}wake()}else open()});
 on(document.querySelector('#memory-object'),'click',open);
 on(turn,'click',()=>{const flipped=card.dataset.turned!=='true';card.dataset.turned=String(flipped);turn.textContent=flipped?'See the photograph':'Turn it over';document.querySelector('.memory-front').setAttribute('aria-hidden',String(flipped));document.querySelector('.memory-back').setAttribute('aria-hidden',String(!flipped))});
 on(document.querySelector('#close-memory'),'click',()=>dialog.close());on(dialog,'click',e=>{if(e.target===dialog)dialog.close()});on(dialog,'close',()=>{document.body.classList.remove('memory-open');returnFocus?.focus({preventScroll:true});wake()});
 return {draw(ctx,canvas,source){const s=state(),next=s.p>.255&&s.p<.30?'little':s.p>.34&&s.p<.411?'waiting':s.p>.565&&s.p<.64?'us':'';if(next!==mode){mode=next;frost()}
 action.hidden=!mode;document.querySelector('#memory-object').hidden=!['little','us'].includes(mode);action.textContent=mode==='waiting'?(cleared?'Let the mist return':'Clear the glass'):'Stay a little';
 if(mode!=='waiting')return;const r=area(s),a=smooth(progress(s.p,.34,.348))*(1-smooth(progress(s.p,.403,.411)));if(a<=0)return;
 f.globalCompositeOperation='source-over';f.clearRect(0,0,640,480);f.filter='blur(5px)';const paint=(image,alpha=1)=>{if(!image)return;if(image.filmImage){paint(image.fallback,alpha);paint(image.filmImage,alpha*image.blend);return}const b=cover(image.width,image.height,s.w,s.h,s.mobile?.77:.5);f.globalAlpha=alpha;f.drawImage(image,(r.x-b.x)/b.w*image.width,(r.y-b.y)/b.h*image.height,r.w/b.w*image.width,r.h/b.h*image.height,0,0,640,480);f.globalAlpha=1};paint(source);f.filter='none';f.fillStyle='#b6c6c330';f.fillRect(0,0,640,480);f.globalCompositeOperation='destination-in';f.drawImage(mask,0,0);
 ctx.save();ctx.globalAlpha=a*.72;ctx.drawImage(mist,r.x,r.y,r.w,r.h);ctx.restore();
 },close(){if(dialog.open)dialog.close()}};
}
